# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch as t

# Create random tensor
tensor1 = t.rand((7,7))
tensor1

tensor([[0.0513, 0.4521, 0.6770, 0.1629, 0.4022, 0.4646, 0.6428],
        [0.7431, 0.9699, 0.0961, 0.9057, 0.9734, 0.0831, 0.5700],
        [0.9680, 0.8564, 0.1310, 0.9817, 0.1148, 0.2855, 0.1209],
        [0.2183, 0.9451, 0.2141, 0.8068, 0.1912, 0.1064, 0.9076],
        [0.2057, 0.7896, 0.9049, 0.3683, 0.6881, 0.2334, 0.5678],
        [0.5971, 0.2023, 0.7722, 0.8718, 0.7404, 0.0389, 0.2314],
        [0.3171, 0.7697, 0.3226, 0.7146, 0.4631, 0.2344, 0.2404]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor2 = t.rand((1,7))
# Perform matrix multiplication 
tensor1 @ tensor2.T

tensor([[0.7231],
        [0.6994],
        [0.6749],
        [0.6268],
        [1.0018],
        [0.9508],
        [0.6824]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
t.manual_seed(0)

# Create two random tensors
a = t.rand((7,7))
b = t.rand(1,7)


# Matrix multiply tensors
a @ b.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
t.mps.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
t.mps.manual_seed(42)

# Check for access to GPU
device = 'mps' if t.backends.mps.is_available() else 'cpu'
# Create two random tensors on GPU
a = t.rand((7,7), device=device)
b = t.rand((1,7), device=device)
a, b

(tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01, 3.3936e-01, 4.5596e-01,
          6.7508e-01],
         [4.4060e-04, 4.0876e-01, 1.7912e-01, 5.9732e-01, 8.4722e-01, 4.6701e-01,
          2.0730e-01],
         [4.2425e-01, 7.3200e-01, 7.9633e-01, 2.4987e-01, 9.2944e-01, 3.5299e-01,
          9.5028e-01],
         [6.7541e-01, 7.9429e-01, 5.8153e-01, 3.0577e-02, 7.8344e-01, 8.6078e-01,
          8.9267e-01],
         [7.6115e-01, 7.6772e-01, 5.8025e-01, 4.3897e-01, 1.9158e-01, 5.0489e-01,
          2.6444e-01],
         [6.4470e-01, 3.7207e-01, 8.9172e-01, 8.0635e-01, 6.0971e-01, 6.0305e-01,
          9.0344e-02],
         [9.7051e-01, 8.7768e-01, 6.2648e-02, 1.2800e-01, 2.2489e-01, 8.6703e-01,
          5.0311e-01]], device='mps:0'),
 tensor([[0.0661, 0.3270, 0.5155, 0.2259, 0.8333, 0.5891, 0.2452]],
        device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
c = a @ b.T
c

tensor([[1.4246],
        [1.3929],
        [1.9497],
        [1.9898],
        [1.2215],
        [1.6916],
        [1.2338]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max, # Find min
c.max(), c.min()

(tensor(1.9898, device='mps:0'), tensor(1.2215, device='mps:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max, # Find arg min
c.argmax(), c.argmin()



(tensor(3, device='mps:0'), tensor(4, device='mps:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
t.mps.manual_seed(7)

# Create random tensor
a = t.rand((1,1,1,10), device=device)

# Remove single dimensions
b = t.rand(10)

# Print out tensors and their shapes
a, a.shape, b, b.shape

(tensor([[[[0.7544, 0.7100, 0.7095, 0.4036, 0.5627, 0.0098, 0.0498, 0.7344,
            0.9472, 0.2643]]]], device='mps:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745,
         0.4369]),
 torch.Size([10]))